spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rinconesmendoza?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        thymeleaf:
            cache: false
    server:
        port: 8080 